version: '3.8'

services:
  portainer:
    image: portainer/portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 9000:9000
      - 8000:8000
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=portainer.${SERVER_HOST_NAME}
  wiki:
    image: 'bitnami/dokuwiki:0'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - wiki:/bitnami
    environment:
      - VIRTUAL_HOST=${SERVER_HOST_NAME}
      - CERT_NAME=root.${SERVER_HOST_NAME}
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${SERVER_CERTS_PATH}:/etc/nginx/certs:ro
      - ${SERVER_VHOSTD_PATH}:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

volumes: 
  wiki:
    name: ${WIKI_VOLUME}

networks:
  proxy:
    external: 
      name: ${SERVER_DOCKER_NETWORK}
