#!/bin/bash

# Script backup wiki

DEFAULT_BACKUP=${SERVER_BACKUP_PATH:-.}
BACKUP=${1:-$DEFAULT_BACKUP}

EXCLUDE=""
EXCLUDE=" $EXCLUDE --exclude data/cache/"
EXCLUDE=" $EXCLUDE --exclude data/index/"
EXCLUDE=" $EXCLUDE --exclude data/locks/"
EXCLUDE=" $EXCLUDE --exclude data/tmp/"

echo Backup wiki to $SERVER_BACKUP_PATH/wiki

/usr/bin/docker run --rm \
    -v wiki:/data:ro \
    -v ${BACKUP}:/backup \
    eeacms/rsync \
    rsync -av --delete $EXCLUDE /data/dokuwiki/ /backup/wiki/
